/// <reference types="Cypress"/>
require('cypress-plugin-tab')
var Fakerator = require("fakerator");
var fakerator = Fakerator("es-ES");

describe("Crear Persona Natural", () => {

  it("crear cliente con RUC", () => {
    cy.visit(`${Cypress.env('baseUrl')}login`)
    cy.wait(5000)
    cy.get(".dropdown-toggle").click()
    cy.get(".dropdown-menu > :nth-child(3) > a").click()
    cy.get("#login-org").type(Cypress.env('org'))
    cy.get("#login-rut").type(Cypress.env('rut'))
    cy.get("#login-password").type(Cypress.env('password'))
    cy.get("#login-form > .btn-lg").click()
    cy.wait(7000)
    cy.get("#btn-caucion").click()
    cy.wait(5000)
    cy.visit(`${Cypress.env('baseUrl')}mantenedor-cliente?option=FORMCLIENTE`)
    cy.get('[formcontrolname="identificationType"]').select('RUC')
    cy.get('[formcontrolname="identNumber"]').type(`20${fakerator.random.number(100000000, 199999999)}`)
    cy.get('[formcontrolname="tipoPersona"]').select('Jurídica')
    // cy.pause()
    cy.get('[formcontrolname="tipoPersonaJuridica"]').trigger('click')
    cy.wait(5000)
    cy.get('[formcontrolname="tipoPersonaJuridica"]').select('COOPERATIVA')
    cy.get('[formcontrolname="razonSocial"]').type(`TEST ${fakerator.company.name()}`)
    cy.get('[formcontrolname="fechaConstitucion"]').click().type(`0${fakerator.random.number(1, 9)}/0${fakerator.random.number(1, 9)}/2021`).type('{enter}')
    cy.get('[formcontrolname="tipoEmpresa"]').select('Privada')
    cy.get('[formcontrolname="nivelEmpresa"]').select('Pequeña Empresa')
    cy.get('[formcontrolname="nroEmpleados"]').type(fakerator.random.number(10, 40))
    cy.get('.btn.btn-default.btn-secondary.form-control.ui-select-toggle').click({force: true, multiple: true}).wait(1000)
    cy.get('div > ul > li:nth-child(4) > div > a > div').click({force: true, multiple: true })
    cy.get('[formcontrolname="regimenDD"]').select('GENERAL')
    cy.get('[formcontrolname="condicionSO"]').select('NO')
    cy.get('[id="telefonoPrincipal"]').type(fakerator.phone.number())
    cy.get('[id="telefonoAdicional"]').type(fakerator.phone.number())
    cy.get('[id="correoElectronico"]').type(fakerator.internet.email())
    cy.get('[formcontrolname="correoElectronicoFacturacion"]').type(fakerator.internet.email())
    cy.get('[formcontrolname="pais"]').select('LIMA').wait(1000)
    cy.get('[formcontrolname="estado"]').select('BARRANCA').wait(1000)
    cy.get('[formcontrolname="distrito"]').select('PARAMONGA')
    cy.get('[formcontrolname="direccion"]').type(fakerator.address.street())
    cy.get('[formcontrolname="tipoCuenta"]').select('Cuenta corriente')
    cy.get('[formcontrolname="banco"]').select('Banco Falabella')
    cy.get('[formcontrolname="nroCuenta"]').type(fakerator.random.number(10000000000, 19999999999))
    cy.get('.form-check-input[value="GN"]').click()

    cy.get('#btn-create-representantes').click()
    cy.get('#tipoIdentificacion-repr').select('RUC')
    cy.get('#nroIdentificacion-repr').type(`10${fakerator.random.number(100000000, 199999999)}`)
    cy.get('#dsNombres-repr').type(fakerator.names.name())
    cy.get('#genero-repr').select('Masculino')
    cy.get('#cargo-repr').select('CEO / Gerente General')


    cy.get('#btn-create-contactos').click()
    cy.get('[formcontrolname="tipoContacto"]').select('Aval')
    cy.get('[formcontrolname="tipoPersona"][ng-reflect-is-disabled="false"]').select('Jurídica')
    cy.get('#razonSocial-contactos').type(fakerator.company.name())
    cy.get('#tipoIdentificacion-contactos').select('RUC')
    cy.get('#nroIdentificacion-contactos').type(`20${fakerator.random.number(100000000, 199999999)}`)
    cy.get('#direccion-contactos').type(fakerator.address.street())
    cy.get('#numTelefono-contactos').type(fakerator.phone.number())
    cy.get('#extension-contactos').type(fakerator.random.number(200, 250))
    cy.get('#celular-contactos').type(fakerator.phone.number())
    cy.get('#email-contactos').type(fakerator.internet.email())
    cy.get('#tipoIdentRepr-reprContactos').select('RUC')
    cy.get('#identNumberRepr-reprContactos').type(`10${fakerator.random.number(100000000, 199999999)}`)
    cy.get('#dsNombresRepr-reprContactos').type(fakerator.names.name())
    cy.get('#cargo-reprContactos').select('CEO / Gerente General')

    cy.get('#btn-create-accionistas').click()
    cy.get('#btn-create-accionistas').click()

    cy.get('#tipoPersona-accion-1').select('Jurídica')
    cy.get('#razonSocial-accion-1').type(fakerator.company.name())
    cy.get('#direccion-accion-1').type(fakerator.address.street())
    cy.get('#tipoIdentificacion-accion-1').select('RUC')
    cy.get('#nroIdentificacion-accion-1').type(`20${fakerator.random.number(100000000, 199999999)}`)
    cy.get('#participacion-accion-1').type(50)
    cy.get('#btn-createRepr-accion-1').click()
    cy.get('#tipoIdentRepr-accion-1').select('RUC')
    cy.get('#identNumberRepr-accion-1').type(`20${fakerator.random.number(100000000, 199999999)}`)
    cy.get('#dsNombresRepr-accion-1').type(fakerator.names.name())
    cy.get('#cargo-accion-1').select('CEO / Gerente General')

    cy.get('#tipoPersona-accion-2').select('Jurídica')
    cy.get('#razonSocial-accion-2').type(fakerator.company.name())
    cy.get('#direccion-accion-2').type(fakerator.address.street())
    cy.get('#tipoIdentificacion-accion-2').select('RUC')
    cy.get('#nroIdentificacion-accion-2').type(`20${fakerator.random.number(100000000, 199999999)}`)
    cy.get('#participacion-accion-2').type(50)
    cy.get('#btn-createRepr-accion-2').click()
    cy.get('#tipoIdentRepr-accion-2').select('RUC')
    cy.get('#identNumberRepr-accion-2').type(`20${fakerator.random.number(100000000, 199999999)}`)
    cy.get('#dsNombresRepr-accion-2').type(fakerator.names.name())
    cy.get('#cargo-accion-2').select('CEO / Gerente General')
  });

});